/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Table.glb 
*/

import React, { useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {motion} from 'framer-motion-3d'
import { useScroll } from 'framer-motion'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Table.glb')
  const {scrollYProgress} = useScroll();
  const [animate, setAnimate] = useState(false);
  
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={15} decay={2} position={[-1.04, 4.862, 4.255]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={15} decay={2} position={[-1.04, 4.772, 0.025]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={15} decay={2} position={[-1.04, 4.625, -4.047]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={15} decay={2} position={[2.209, 3.247, 4.857]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={15} decay={2} position={[2.329, 3.247, 0.914]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={15} decay={2} position={[2.329, 3.247, -3.626]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={30} decay={2} position={[10.329, 3.247, 2.626]} rotation={[-Math.PI / 2, 0, 0]} />
      <motion.mesh 
      initial={{
        x: -100,
        opacity: 0
      }}
      animate={{
        x: 0,
        opacity: 1
      }}
      transition={{
        delay: 0.8,
        duration: 1.2
      }}
      geometry={nodes.Circle002.geometry} material={materials['Material.009']} position={[-1.04, 8.69, 4.255]} scale={0.217} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.009']} position={[-1.04, 8.69, 0.025]} scale={0.217} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.009']} position={[-1.04, 8.69, -4.047]} scale={0.217} />
      <group position={[-0.85, 2.764, 5.531]} rotation={[-0.023, -0.97, -1.564]} scale={0.145}>
        <mesh geometry={nodes.Cube073.geometry} material={materials['Loaf.001']} />
        <mesh geometry={nodes.Cube073_1.geometry} material={materials['Slice.001']} />
        <mesh geometry={nodes.Cube073_2.geometry} material={materials['Ceramic.001']} />
      </group>
      <group position={[0.795, 0.443, 5.176]} scale={0.041}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.014']} />
      </group>
      <group position={[0.795, 0.443, 2.295]} scale={0.041}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.014']} />
      </group>
      <mesh geometry={nodes.thirdChair.geometry} material={materials.wood} position={[0.416, 0.409, 1.397]} rotation={[0, 0.078, 0]} scale={0.264} />
      <mesh geometry={nodes.table.geometry} material={materials['Kitchen Top.001']} position={[-1.158, 2.042, 0.241]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.944, 1.391, 1.724]} />
      <group position={[-0.763, 2.784, 2.345]} rotation={[0.519, -0.672, -0.151]} scale={[0.011, 0.01, 0.011]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials.tomato} />
        <mesh geometry={nodes.Cylinder005_4.geometry} material={materials.matar} />
      </group>
      <group position={[-0.73, 2.943, -0.243]} scale={0.061}>
        <mesh geometry={nodes.Circle008.geometry} material={materials.Porcelain} />
        <mesh geometry={nodes.Circle008_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Circle008_2.geometry} material={materials.Sauce} />
        <mesh geometry={nodes.Circle008_3.geometry} material={materials.Sauce_Bits} />
        <mesh geometry={nodes.Circle008_4.geometry} material={materials.Lumpia_Material} />
      </group>
      <group position={[-1.789, 2.762, -5.129]} scale={0.181}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.plate} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['cheese-filled-omelette-tomatoes-scallions-720x540']} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-0.613, 2.762, -5.129]} scale={0.181}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials.plate} />
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder009_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder009_3.geometry} material={materials['cheese-filled-omelette-tomatoes-scallions-720x540']} />
        <mesh geometry={nodes.Cylinder009_4.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.thirdChair001.geometry} material={materials['Material.014']} position={[0.416, 0.409, 1.397]} rotation={[0, 0.078, 0]} scale={0.264} />
      {/* <mesh geometry={nodes.Plane.geometry} material={materials.Material} scale={-14.726} /> */}
    </group>
  )
}

useGLTF.preload('/Table.glb')
